### ISSUE TITLE
Invalid or corrupt on json file

### ISSUE THREAD

**Issue by Chen-kaiyuan** [Loadium/postman2jmx#1]
hi guys:
             I don't know what's wrong.

![image](https://user-images.githubusercontent.com/17740259/66998180-5df5d300-f106-11e9-90f8-8357c645c1d6.png)

[121.postman_collection.zip](https://github.com/Loadium/postman2jmx/files/3738538/121.postman_collection.zip)

**Comment by erdoganonur** [comment]
@selcuksozuer

**Comment by balajeeoshift** [comment]
Please use the command
java -jar Postman2Jmx.jar 121.postman_collection.json 121.jmx

**Comment by bilalvdemir** [comment]
@Chen-kaiyuan please use this command:
`java -jar Postman2Jmx.jar 121.postman_collection.json 121.jmx`

thanks @balajeeoshift
